### ISSUE TITLE
Interactive mode fails on a fresh install

### ISSUE THREAD

**Issue by weinberz** [fastai/fastec2#15]
I've just installed fe2 as described in the howto article. When attempting to enter the REPL, I get the following error:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/py37/bin/fe2", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/py37/lib/python3.7/site-packages/fastec2/__init__.py", line 8, in main
    if len(sys.argv)>=2 and sys.argv[1]=='i': interact(*sys.argv[2:])
NameError: name 'interact' is not defined

**Comment by dthiagarajan** [comment]
You can fix this by adding the following in your `fastec2/ec2.py` file:

Change `__all__` to be:

```
__all__ = 'EC2 result results snake2camel make_filter listify interact'.split()
```
