### ISSUE TITLE
fastec2/scripts.py is missing

### ISSUE THREAD

**Issue by knok** [fastai/fastec2#6]
Currentry, fe2 not work on my machine.
```
% fe2
Traceback (most recent call last):
  File "/opt/366p/bin/fe2", line 6, in <module>
    from fastec2 import main
  File "/opt/366p/lib/python3.6/site-packages/fastec2/__init__.py", line 4, in <module>
    from .ec2 import *
  File "/opt/366p/lib/python3.6/site-packages/fastec2/ec2.py", line 10, in <module>
    from .scripts import *
ModuleNotFoundError: No module named 'fastec2.scripts'
```
It seems that fe2 command requires fastec2/scripts.py file, but not exist.

Commented out the line 10 of ec2.py, it works.

**Comment by aglavers** [comment]
Same issue. Comment  line 10 of ec2.py, works.

**Comment by jph00** [comment]
Should be fixed now.
